diff a/rust/load/Dockerfile b/rust/load/Dockerfile	(rejected hunks)
@@ -16,10 +16,16 @@ RUN --mount=type=cache,sharing=locked,target=/chroma/target/ \
     if [ "$RELEASE_MODE" = "1" ]; then cargo build --bin chroma-load --release; else cargo build --bin chroma-load; fi && \
     if [ "$RELEASE_MODE" = "1" ]; then mv target/release/chroma-load ./chroma-load; else mv target/debug/chroma-load ./chroma-load; fi
 
+RUN --mount=type=cache,sharing=locked,target=/chroma/target/ \
+    --mount=type=cache,sharing=locked,target=/usr/local/cargo/registry/ \
+    if [ "$RELEASE_MODE" = "1" ]; then cargo build --bin chroma-load-start --release; else cargo build --bin chroma-load-start; fi && \
+    if [ "$RELEASE_MODE" = "1" ]; then mv target/release/chroma-load-start ./chroma-load-start; else mv target/debug/chroma-load-start ./chroma-load-start; fi
+
 FROM debian:bookworm-slim AS runner
 RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
 COPY --from=builder /chroma/rust/load/chroma_load_config.yaml .
 
 FROM runner AS load_service
 COPY --from=load_service_builder /chroma/chroma-load .
+COPY --from=load_service_builder /chroma/chroma-load-start .
 ENTRYPOINT [ "./chroma-load" ]
