diff a/Dockerfile b/Dockerfile	(rejected hunks)
@@ -11,9 +11,10 @@ RUN apt-get update --fix-missing && apt-get install -y --fix-missing \
     unzip \
     curl \
     make && \
+    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
     rm -rf /var/lib/apt/lists/* && \
     mkdir /install
-
+ENV PATH="/root/.cargo/bin:$PATH"
 # Install specific Protobuf compiler (v28.2)
 RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip && \
     unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local/ && \
@@ -25,18 +26,21 @@ WORKDIR /install
 
 COPY ./requirements.txt requirements.txt
 
+RUN --mount=type=cache,target=/root/.cache/pip pip install maturin cffi patchelf
 RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade --prefix="/install" -r requirements.txt
 RUN --mount=type=cache,target=/root/.cache/pip if [ "$REBUILD_HNSWLIB" = "true" ]; then pip install --no-binary :all: --force-reinstall --prefix="/install" chroma-hnswlib; fi
 
 # Install gRPC tools for Python with fixed version
 RUN pip install grpcio==1.58.0 grpcio-tools==1.58.0
-
 # Copy source files to build Protobufs
 COPY ./ /chroma
 
 # Generate Protobufs
 WORKDIR /chroma
 RUN make -C idl proto_python
+RUN python3 -m maturin build
+RUN pip uninstall chromadb -y
+RUN pip install --prefix="/install" --find-links target/wheels/ --upgrade  chromadb
 
 FROM python:3.11-slim-bookworm AS final
 
@@ -64,4 +68,5 @@ ENV CHROMA_TIMEOUT_KEEP_ALIVE=30
 EXPOSE 8000
 
 ENTRYPOINT ["/docker_entrypoint.sh"]
-CMD [ "--workers ${CHROMA_WORKERS} --host ${CHROMA_HOST_ADDR} --port ${CHROMA_HOST_PORT} --proxy-headers --log-config ${CHROMA_LOG_CONFIG} --timeout-keep-alive ${CHROMA_TIMEOUT_KEEP_ALIVE}"]
+CMD [ "--workers ${CHROMA_WORKERS} --host ${CHROMA_HOST_ADDR} --port ${CHROMA_HOST_PORT} --proxy-headers --reload --log-config ${CHROMA_LOG_CONFIG} --timeout-keep-alive ${CHROMA_TIMEOUT_KEEP_ALIVE}"]
+
