name: Release Development JavaScript Client

on:
  push:
    branches:
      - main
jobs:
  test:
    name: JavaScript client tests with WarpBuild
    uses: ./.github/workflows/_javascript-client-tests.yml
